//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int appointmentID { get; set; }
        public string appointmentUUID { get; set; }
        public Nullable<int> candidateReferenceID { get; set; }
        public Nullable<int> clientContactReferenceID { get; set; }
        public string communicationMethod { get; set; }
        public System.DateTime dateAdded { get; set; }
        public System.DateTime dateBegin { get; set; }
        public System.DateTime dateEnd { get; set; }
        public Nullable<System.DateTime> dateLastModified { get; set; }
        public string description { get; set; }
        public Nullable<short> isAllDay { get; set; }
        public short isDeleted { get; set; }
        public short isPrivate { get; set; }
        public Nullable<int> jobOrderID { get; set; }
        public string location { get; set; }
        public short notificationMinutes { get; set; }
        public int ownerID { get; set; }
        public Nullable<int> parentAppointmentID { get; set; }
        public Nullable<int> placementID { get; set; }
        public Nullable<short> recurrenceDayBits { get; set; }
        public Nullable<short> recurrenceFrequency { get; set; }
        public string recurrenceStyle { get; set; }
        public string recurrenceType { get; set; }
        public string subject { get; set; }
        public string type { get; set; }
    }
}
