//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int userID { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public Nullable<int> candidateSourceID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public string certifications { get; set; }
        public string comments { get; set; }
        public string companyName { get; set; }
        public string companyURL { get; set; }
        public Nullable<int> customInt1 { get; set; }
        public Nullable<int> customInt2 { get; set; }
        public Nullable<int> customInt3 { get; set; }
        public Nullable<System.DateTime> customDate1 { get; set; }
        public Nullable<System.DateTime> customDate2 { get; set; }
        public Nullable<System.DateTime> customDate3 { get; set; }
        public Nullable<double> customFloat1 { get; set; }
        public Nullable<double> customFloat2 { get; set; }
        public Nullable<double> customFloat3 { get; set; }
        public string customText1 { get; set; }
        public string customText2 { get; set; }
        public string customText3 { get; set; }
        public string customText4 { get; set; }
        public string customText5 { get; set; }
        public string customText6 { get; set; }
        public string customText7 { get; set; }
        public string customText8 { get; set; }
        public string customText9 { get; set; }
        public string customText10 { get; set; }
        public string customText11 { get; set; }
        public string customText12 { get; set; }
        public string customText13 { get; set; }
        public string customText14 { get; set; }
        public string customText15 { get; set; }
        public string customText16 { get; set; }
        public string customText17 { get; set; }
        public string customText18 { get; set; }
        public string customText19 { get; set; }
        public string customText20 { get; set; }
        public string customTextBlock1 { get; set; }
        public string customTextBlock2 { get; set; }
        public string customTextBlock3 { get; set; }
        public string customTextBlock4 { get; set; }
        public string customTextBlock5 { get; set; }
        public System.DateTime dateAdded { get; set; }
        public Nullable<System.DateTime> dateAvailable { get; set; }
        public Nullable<System.DateTime> dateAvailableEnd { get; set; }
        public Nullable<System.DateTime> dateI9Expiration { get; set; }
        public Nullable<System.DateTime> dateLastComment { get; set; }
        public Nullable<System.DateTime> dateNextCall { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public Nullable<decimal> dayRate { get; set; }
        public Nullable<decimal> dayRateLow { get; set; }
        public string degreeList { get; set; }
        public string description { get; set; }
        public string desiredLocations { get; set; }
        public string disability { get; set; }
        public string educationDegree { get; set; }
        public string email { get; set; }
        public string email2 { get; set; }
        public string email3 { get; set; }
        public string employeeType { get; set; }
        public string employmentPreference { get; set; }
        public string ethnicity { get; set; }
        public Nullable<int> experience { get; set; }
        public string externalID { get; set; }
        public string fax { get; set; }
        public string fax2 { get; set; }
        public string fax3 { get; set; }
        public Nullable<decimal> federalAddtionalWitholdingsAmount { get; set; }
        public Nullable<short> federalExemptions { get; set; }
        public string federalFilingStatus { get; set; }
        public string firstName { get; set; }
        public string gender { get; set; }
        public Nullable<decimal> hourlyRate { get; set; }
        public Nullable<decimal> hourlyRateLow { get; set; }
        public Nullable<short> I9OnFile { get; set; }
        public short isDeleted { get; set; }
        public short isEditable { get; set; }
        public string lastName { get; set; }
        public Nullable<int> linkedPersonID { get; set; }
        public Nullable<decimal> localAddtionalWitholdingsAmount { get; set; }
        public Nullable<short> localExemptions { get; set; }
        public string localFilingStatus { get; set; }
        public string localTaxCode { get; set; }
        public Nullable<short> massMailOptOut { get; set; }
        public string middleName { get; set; }
        public string mobile { get; set; }
        public string name { get; set; }
        public string namePrefix { get; set; }
        public string nameSuffix { get; set; }
        public string nickName { get; set; }
        public Nullable<int> numCategories { get; set; }
        public Nullable<int> numOwners { get; set; }
        public string occupation { get; set; }
        public int ownerID { get; set; }
        public string pager { get; set; }
        public string paperWorkOnFile { get; set; }
        public string phone { get; set; }
        public string phone2 { get; set; }
        public string phone3 { get; set; }
        public string preferredContact { get; set; }
        public Nullable<int> privateLabelID { get; set; }
        public string recentClientList { get; set; }
        public string referredBy { get; set; }
        public Nullable<int> referredByPersonID { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<decimal> salaryLow { get; set; }
        public string secondaryAddress1 { get; set; }
        public string secondaryAddress2 { get; set; }
        public string secondaryCity { get; set; }
        public string secondaryState { get; set; }
        public string secondaryZip { get; set; }
        public string secondaryCountry { get; set; }
        public string skillSet { get; set; }
        public Nullable<short> smsOptIn { get; set; }
        public string source { get; set; }
        public string ssn { get; set; }
        public Nullable<decimal> stateAddtionalWitholdingsAmount { get; set; }
        public Nullable<short> stateExemptions { get; set; }
        public string stateFilingStatus { get; set; }
        public string status { get; set; }
        public string taxID { get; set; }
        public string taxState { get; set; }
        public Nullable<short> timeZoneOffsetEST { get; set; }
        public Nullable<short> travelLimit { get; set; }
        public string type { get; set; }
        public string userName { get; set; }
        public string userType { get; set; }
        public string veteran { get; set; }
        public Nullable<short> willRelocate { get; set; }
        public Nullable<short> workAuthorized { get; set; }
        public string workPhone { get; set; }
    }
}
