//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateWorkHistory
    {
        public int CandidateWorkHistoryID { get; set; }
        public Nullable<double> bonus { get; set; }
        public int candidateID { get; set; }
        public Nullable<int> clientCorporationID { get; set; }
        public string comments { get; set; }
        public Nullable<double> commission { get; set; }
        public string companyName { get; set; }
        public Nullable<System.DateTime> customDate1 { get; set; }
        public Nullable<System.DateTime> customDate2 { get; set; }
        public Nullable<System.DateTime> customDate3 { get; set; }
        public Nullable<System.DateTime> customDate4 { get; set; }
        public Nullable<System.DateTime> customDate5 { get; set; }
        public Nullable<double> customFloat1 { get; set; }
        public Nullable<double> customFloat2 { get; set; }
        public Nullable<double> customFloat3 { get; set; }
        public Nullable<double> customFloat4 { get; set; }
        public Nullable<double> customFloat5 { get; set; }
        public Nullable<int> customInt1 { get; set; }
        public Nullable<int> customInt2 { get; set; }
        public Nullable<int> customInt3 { get; set; }
        public Nullable<int> customInt4 { get; set; }
        public Nullable<int> customInt5 { get; set; }
        public string customText1 { get; set; }
        public string customText2 { get; set; }
        public string customText3 { get; set; }
        public string customText4 { get; set; }
        public string customText5 { get; set; }
        public string customTextBlock1 { get; set; }
        public string customTextBlock2 { get; set; }
        public string customTextBlock3 { get; set; }
        public System.DateTime dateAdded { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public short isDeleted { get; set; }
        public short isLastJob { get; set; }
        public Nullable<int> jobOrderID { get; set; }
        public Nullable<int> placementID { get; set; }
        public Nullable<decimal> salary1 { get; set; }
        public Nullable<decimal> salary2 { get; set; }
        public string salaryType { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public string terminationReason { get; set; }
        public string title { get; set; }
    }
}
