//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCorporation
    {
        public int clientCorporationID { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public decimal annualRevenue { get; set; }
        public string billingAddress1 { get; set; }
        public string billingAddress2 { get; set; }
        public string billingCity { get; set; }
        public string billingState { get; set; }
        public string billingZip { get; set; }
        public string billingCountry { get; set; }
        public string billingContact { get; set; }
        public string billingFrequency { get; set; }
        public string billingPhone { get; set; }
        public string businessSectorList { get; set; }
        public string companyDescription { get; set; }
        public string companyURL { get; set; }
        public string competitors { get; set; }
        public string culture { get; set; }
        public Nullable<System.DateTime> customDate1 { get; set; }
        public Nullable<System.DateTime> customDate2 { get; set; }
        public Nullable<System.DateTime> customDate3 { get; set; }
        public Nullable<double> customFloat1 { get; set; }
        public Nullable<double> customFloat2 { get; set; }
        public Nullable<double> customFloat3 { get; set; }
        public Nullable<int> customInt1 { get; set; }
        public Nullable<int> customInt2 { get; set; }
        public Nullable<int> customInt3 { get; set; }
        public string customText1 { get; set; }
        public string customText2 { get; set; }
        public string customText3 { get; set; }
        public string customText4 { get; set; }
        public string customText5 { get; set; }
        public string customText6 { get; set; }
        public string customText7 { get; set; }
        public string customText8 { get; set; }
        public string customText9 { get; set; }
        public string customText10 { get; set; }
        public string customText11 { get; set; }
        public string customText12 { get; set; }
        public string customText13 { get; set; }
        public string customText14 { get; set; }
        public string customText15 { get; set; }
        public string customText16 { get; set; }
        public string customText17 { get; set; }
        public string customText18 { get; set; }
        public string customText19 { get; set; }
        public string customText20 { get; set; }
        public string customTextBlock1 { get; set; }
        public string customTextBlock2 { get; set; }
        public string customTextBlock3 { get; set; }
        public string customTextBlock4 { get; set; }
        public string customTextBlock5 { get; set; }
        public System.DateTime dateAdded { get; set; }
        public Nullable<System.DateTime> dateFounded { get; set; }
        public Nullable<int> departmentID { get; set; }
        public string externalID { get; set; }
        public string fax { get; set; }
        public double feeArrangement { get; set; }
        public string funding { get; set; }
        public string industryList { get; set; }
        public short isDeleted { get; set; }
        public string invoiceFormat { get; set; }
        public string name { get; set; }
        public string notes { get; set; }
        public int numEmployees { get; set; }
        public short numOffices { get; set; }
        public string ownerShip { get; set; }
        public Nullable<int> parentClientCorporationID { get; set; }
        public string phone { get; set; }
        public string revenue { get; set; }
        public string status { get; set; }
        public Nullable<double> taxRate { get; set; }
        public string tickerSymbol { get; set; }
        public Nullable<short> workWeekStart { get; set; }
    }
}
