//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientContact
    {
        public int userID { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string certifications { get; set; }
        public int clientCorporationID { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> customDate1 { get; set; }
        public Nullable<System.DateTime> customDate2 { get; set; }
        public Nullable<System.DateTime> customDate3 { get; set; }
        public Nullable<double> customFloat1 { get; set; }
        public Nullable<double> customFloat2 { get; set; }
        public Nullable<double> customFloat3 { get; set; }
        public Nullable<int> customInt1 { get; set; }
        public Nullable<int> customInt2 { get; set; }
        public Nullable<int> customInt3 { get; set; }
        public string customText1 { get; set; }
        public string customText2 { get; set; }
        public string customText3 { get; set; }
        public string customText4 { get; set; }
        public string customText5 { get; set; }
        public string customText6 { get; set; }
        public string customText7 { get; set; }
        public string customText8 { get; set; }
        public string customText9 { get; set; }
        public string customText10 { get; set; }
        public string customText11 { get; set; }
        public string customText12 { get; set; }
        public string customText13 { get; set; }
        public string customText14 { get; set; }
        public string customText15 { get; set; }
        public string customText16 { get; set; }
        public string customText17 { get; set; }
        public string customText18 { get; set; }
        public string customText19 { get; set; }
        public string customText20 { get; set; }
        public string customTextBlock1 { get; set; }
        public string customTextBlock2 { get; set; }
        public string customTextBlock3 { get; set; }
        public string customTextBlock4 { get; set; }
        public string customTextBlock5 { get; set; }
        public System.DateTime dateAdded { get; set; }
        public Nullable<System.DateTime> dateLastVisit { get; set; }
        public string description { get; set; }
        public string desiredCategories { get; set; }
        public string desiredSkills { get; set; }
        public string desiredSpecialties { get; set; }
        public string division { get; set; }
        public string email { get; set; }
        public string email2 { get; set; }
        public string email3 { get; set; }
        public string externalID { get; set; }
        public string fax { get; set; }
        public string fax2 { get; set; }
        public string fax3 { get; set; }
        public string firstName { get; set; }
        public Nullable<short> isDayLightSavings { get; set; }
        public short isDeleted { get; set; }
        public string lastName { get; set; }
        public Nullable<int> linkedPersonID { get; set; }
        public Nullable<short> massMailOptOut { get; set; }
        public string middleName { get; set; }
        public string mobile { get; set; }
        public string name { get; set; }
        public string namePrefix { get; set; }
        public string nameSuffix { get; set; }
        public string nickName { get; set; }
        public short numEmployees { get; set; }
        public string occupation { get; set; }
        public string office { get; set; }
        public int ownerID { get; set; }
        public string pager { get; set; }
        public string phone { get; set; }
        public string phone2 { get; set; }
        public string phone3 { get; set; }
        public string preferredContact { get; set; }
        public Nullable<int> referredByPersonID { get; set; }
        public Nullable<int> reportToPersonID { get; set; }
        public string secondaryAddress1 { get; set; }
        public string secondaryAddress2 { get; set; }
        public string secondaryCity { get; set; }
        public string secondaryState { get; set; }
        public string secondaryZip { get; set; }
        public string secondaryCountry { get; set; }
        public Nullable<short> smsOptIn { get; set; }
        public string source { get; set; }
        public string status { get; set; }
        public string type { get; set; }
        public string userName { get; set; }
        public string userType { get; set; }
        public Nullable<int> categoryID { get; set; }
    }
}
