//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousingComplex
    {
        public int HousingComplexID { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public Nullable<int> billingContactID { get; set; }
        public string comments { get; set; }
        public Nullable<int> complexManagerID { get; set; }
        public Nullable<int> complexOwnerID { get; set; }
        public string contactName { get; set; }
        public Nullable<int> customContactID1 { get; set; }
        public Nullable<int> customContactID2 { get; set; }
        public Nullable<int> customContactID3 { get; set; }
        public Nullable<System.DateTime> customDate1 { get; set; }
        public Nullable<System.DateTime> customDate2 { get; set; }
        public Nullable<System.DateTime> customDate3 { get; set; }
        public Nullable<double> customFloat1 { get; set; }
        public Nullable<double> customFloat2 { get; set; }
        public Nullable<double> customFloat3 { get; set; }
        public Nullable<int> customInt1 { get; set; }
        public Nullable<int> customInt2 { get; set; }
        public Nullable<int> customInt3 { get; set; }
        public string customText1 { get; set; }
        public string customText2 { get; set; }
        public string customText3 { get; set; }
        public string customText4 { get; set; }
        public string customText5 { get; set; }
        public string customTextBlock1 { get; set; }
        public string customTextBlock2 { get; set; }
        public string customTextBlock3 { get; set; }
        public string customTextBlock4 { get; set; }
        public string customTextBlock5 { get; set; }
        public System.DateTime dateAdded { get; set; }
        public string fax { get; set; }
        public short isDeleted { get; set; }
        public string name { get; set; }
        public int ownerID { get; set; }
        public string phone { get; set; }
    }
}
