//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public int invoiceItemID { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public string description { get; set; }
        public int invoiceID { get; set; }
        public string payPeriod { get; set; }
        public Nullable<int> placementID { get; set; }
        public double quantity { get; set; }
        public decimal rate { get; set; }
        public Nullable<double> taxRate { get; set; }
        public string unit { get; set; }
        public short wasManuallyCreated { get; set; }
    }
}
