//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrder
    {
        public int jobOrderID { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string benefits { get; set; }
        public Nullable<int> billRateCategoryID { get; set; }
        public string bonusPackage { get; set; }
        public string branchCode { get; set; }
        public string certificationsList { get; set; }
        public Nullable<decimal> clientBillRate { get; set; }
        public int clientContactID { get; set; }
        public int clientCorporationID { get; set; }
        public Nullable<System.DateTime> correlatedCustomDate1 { get; set; }
        public Nullable<System.DateTime> correlatedCustomDate2 { get; set; }
        public Nullable<System.DateTime> correlatedCustomDate3 { get; set; }
        public Nullable<double> correlatedCustomFloat1 { get; set; }
        public Nullable<double> correlatedCustomFloat2 { get; set; }
        public Nullable<double> correlatedCustomFloat3 { get; set; }
        public Nullable<int> correlatedCustomInt1 { get; set; }
        public Nullable<int> correlatedCustomInt2 { get; set; }
        public Nullable<int> correlatedCustomInt3 { get; set; }
        public string correlatedCustomText1 { get; set; }
        public string correlatedCustomText2 { get; set; }
        public string correlatedCustomText3 { get; set; }
        public string correlatedCustomText4 { get; set; }
        public string correlatedCustomText5 { get; set; }
        public string correlatedCustomText6 { get; set; }
        public string correlatedCustomText7 { get; set; }
        public string correlatedCustomText8 { get; set; }
        public string correlatedCustomText9 { get; set; }
        public string correlatedCustomText10 { get; set; }
        public string correlatedCustomTextBlock1 { get; set; }
        public string correlatedCustomTextBlock2 { get; set; }
        public string correlatedCustomTextBlock3 { get; set; }
        public string costCenter { get; set; }
        public Nullable<System.DateTime> customDate1 { get; set; }
        public Nullable<System.DateTime> customDate2 { get; set; }
        public Nullable<System.DateTime> customDate3 { get; set; }
        public Nullable<double> customFloat1 { get; set; }
        public Nullable<double> customFloat2 { get; set; }
        public Nullable<double> customFloat3 { get; set; }
        public Nullable<int> customInt1 { get; set; }
        public Nullable<int> customInt2 { get; set; }
        public Nullable<int> customInt3 { get; set; }
        public string customText1 { get; set; }
        public string customText2 { get; set; }
        public string customText3 { get; set; }
        public string customText4 { get; set; }
        public string customText5 { get; set; }
        public string customText6 { get; set; }
        public string customText7 { get; set; }
        public string customText8 { get; set; }
        public string customText9 { get; set; }
        public string customText10 { get; set; }
        public string customText11 { get; set; }
        public string customText12 { get; set; }
        public string customText13 { get; set; }
        public string customText14 { get; set; }
        public string customText15 { get; set; }
        public string customText16 { get; set; }
        public string customText17 { get; set; }
        public string customText18 { get; set; }
        public string customText19 { get; set; }
        public string customText20 { get; set; }
        public string customTextBlock1 { get; set; }
        public string customTextBlock2 { get; set; }
        public string customTextBlock3 { get; set; }
        public string customTextBlock4 { get; set; }
        public string customTextBlock5 { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<System.DateTime> dateClosed { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public Nullable<System.DateTime> dateLastExported { get; set; }
        public string degreeList { get; set; }
        public string description { get; set; }
        public Nullable<double> durationWeeks { get; set; }
        public string educationDegree { get; set; }
        public string employmentType { get; set; }
        public string externalID { get; set; }
        public Nullable<double> feeArrangement { get; set; }
        public string hoursOfOperation { get; set; }
        public Nullable<double> hoursPerWeek { get; set; }
        public Nullable<short> isClientEditable { get; set; }
        public short isDeleted { get; set; }
        public Nullable<short> isInterviewRequired { get; set; }
        public Nullable<int> isJobcastPublished { get; set; }
        public Nullable<short> isOpen { get; set; }
        public Nullable<short> isPublic { get; set; }
        public string jobBoardList { get; set; }
        public Nullable<short> numOpenings { get; set; }
        public string onSite { get; set; }
        public string optionsPackage { get; set; }
        public Nullable<int> ownerID { get; set; }
        public Nullable<decimal> payRate { get; set; }
        public string publicDescription { get; set; }
        public string publishedZip { get; set; }
        public string reasonClosed { get; set; }
        public string reportTo { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string salaryUnit { get; set; }
        public string skillList { get; set; }
        public string source { get; set; }
        public System.DateTime startDate { get; set; }
        public string status { get; set; }
        public Nullable<double> taxRate { get; set; }
        public string taxStatus { get; set; }
        public string title { get; set; }
        public string travelRequirements { get; set; }
        public Nullable<short> type { get; set; }
        public Nullable<short> willRelocate { get; set; }
        public Nullable<short> willSponsor { get; set; }
        public Nullable<short> yearsRequired { get; set; }
        public Nullable<int> externalCategoryID { get; set; }
        public Nullable<int> workersCompensationRateID { get; set; }
        public Nullable<int> workersCompRateID { get; set; }
        public Nullable<int> responseUserID { get; set; }
    }
}
