//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteEntity
    {
        public int noteID { get; set; }
        public int entityID { get; set; }
        public string entityName { get; set; }
        public short isDeleted { get; set; }
    }
}
