//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacementCommission
    {
        public int commissionID { get; set; }
        public string comments { get; set; }
        public double commissionPercentage { get; set; }
        public System.DateTime dateAdded { get; set; }
        public string externalRecipient { get; set; }
        public double flatPayout { get; set; }
        public double grossMarginPercentage { get; set; }
        public double hourlyPayout { get; set; }
        public short isDeleted { get; set; }
        public int placementID { get; set; }
        public string role { get; set; }
        public Nullable<int> userID { get; set; }
    }
}
