//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placement
    {
        public int placementID { get; set; }
        public Nullable<int> billingClientContactID { get; set; }
        public string billingFrequency { get; set; }
        public string bonusPackage { get; set; }
        public int candidateID { get; set; }
        public Nullable<double> clientBillRate { get; set; }
        public Nullable<double> clientOvertimeRate { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> correlatedCustomDate1 { get; set; }
        public Nullable<System.DateTime> correlatedCustomDate2 { get; set; }
        public Nullable<System.DateTime> correlatedCustomDate3 { get; set; }
        public Nullable<double> correlatedCustomFloat1 { get; set; }
        public Nullable<double> correlatedCustomFloat2 { get; set; }
        public Nullable<double> correlatedCustomFloat3 { get; set; }
        public Nullable<int> correlatedCustomInt1 { get; set; }
        public Nullable<int> correlatedCustomInt2 { get; set; }
        public Nullable<int> correlatedCustomInt3 { get; set; }
        public string correlatedCustomText1 { get; set; }
        public string correlatedCustomText2 { get; set; }
        public string correlatedCustomText3 { get; set; }
        public string correlatedCustomText4 { get; set; }
        public string correlatedCustomText5 { get; set; }
        public string correlatedCustomText6 { get; set; }
        public string correlatedCustomText7 { get; set; }
        public string correlatedCustomText8 { get; set; }
        public string correlatedCustomText9 { get; set; }
        public string correlatedCustomText10 { get; set; }
        public string correlatedCustomTextBlock1 { get; set; }
        public string correlatedCustomTextBlock2 { get; set; }
        public string correlatedCustomTextBlock3 { get; set; }
        public string costCenter { get; set; }
        public Nullable<decimal> customBillRate1 { get; set; }
        public Nullable<decimal> customBillRate2 { get; set; }
        public Nullable<decimal> customBillRate3 { get; set; }
        public Nullable<decimal> customBillRate4 { get; set; }
        public Nullable<decimal> customBillRate5 { get; set; }
        public Nullable<decimal> customBillRate6 { get; set; }
        public Nullable<decimal> customBillRate7 { get; set; }
        public Nullable<decimal> customBillRate8 { get; set; }
        public Nullable<decimal> customBillRate9 { get; set; }
        public Nullable<decimal> customBillRate10 { get; set; }
        public Nullable<System.DateTime> customDate1 { get; set; }
        public Nullable<System.DateTime> customDate2 { get; set; }
        public Nullable<System.DateTime> customDate3 { get; set; }
        public Nullable<double> customFloat1 { get; set; }
        public Nullable<double> customFloat2 { get; set; }
        public Nullable<double> customFloat3 { get; set; }
        public Nullable<int> customInt1 { get; set; }
        public Nullable<int> customInt2 { get; set; }
        public Nullable<int> customInt3 { get; set; }
        public Nullable<decimal> customPayRate1 { get; set; }
        public Nullable<decimal> customPayRate2 { get; set; }
        public Nullable<decimal> customPayRate3 { get; set; }
        public Nullable<decimal> customPayRate4 { get; set; }
        public Nullable<decimal> customPayRate5 { get; set; }
        public Nullable<decimal> customPayRate6 { get; set; }
        public Nullable<decimal> customPayRate7 { get; set; }
        public Nullable<decimal> customPayRate8 { get; set; }
        public Nullable<decimal> customPayRate9 { get; set; }
        public Nullable<decimal> customPayRate10 { get; set; }
        public string customText1 { get; set; }
        public string customText2 { get; set; }
        public string customText3 { get; set; }
        public string customText4 { get; set; }
        public string customText5 { get; set; }
        public string customText6 { get; set; }
        public string customText7 { get; set; }
        public string customText8 { get; set; }
        public string customText9 { get; set; }
        public string customText10 { get; set; }
        public string customText11 { get; set; }
        public string customText12 { get; set; }
        public string customText13 { get; set; }
        public string customText14 { get; set; }
        public string customText15 { get; set; }
        public string customText16 { get; set; }
        public string customText17 { get; set; }
        public string customText18 { get; set; }
        public string customText19 { get; set; }
        public string customText20 { get; set; }
        public string customText21 { get; set; }
        public string customText22 { get; set; }
        public string customText23 { get; set; }
        public string customText24 { get; set; }
        public string customText25 { get; set; }
        public string customText26 { get; set; }
        public string customText27 { get; set; }
        public string customText28 { get; set; }
        public string customText29 { get; set; }
        public string customText30 { get; set; }
        public string customText31 { get; set; }
        public string customText32 { get; set; }
        public string customText33 { get; set; }
        public string customText34 { get; set; }
        public string customText35 { get; set; }
        public string customText36 { get; set; }
        public string customText37 { get; set; }
        public string customText38 { get; set; }
        public string customText39 { get; set; }
        public string customText40 { get; set; }
        public string customTextBlock1 { get; set; }
        public string customTextBlock2 { get; set; }
        public string customTextBlock3 { get; set; }
        public string customTextBlock4 { get; set; }
        public string customTextBlock5 { get; set; }
        public System.DateTime dateAdded { get; set; }
        public System.DateTime dateBegin { get; set; }
        public Nullable<System.DateTime> dateClientEffective { get; set; }
        public Nullable<System.DateTime> dateEffective { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public short daysGuaranteed { get; set; }
        public short daysProRated { get; set; }
        public double durationWeeks { get; set; }
        public string employeeType { get; set; }
        public string employmentType { get; set; }
        public double fee { get; set; }
        public string hoursOfOperation { get; set; }
        public double hoursPerDay { get; set; }
        public Nullable<int> housingManagerID { get; set; }
        public string housingStatus { get; set; }
        public short isDeleted { get; set; }
        public int jobOrderID { get; set; }
        public string optionsPackage { get; set; }
        public Nullable<short> otExemption { get; set; }
        public Nullable<double> otherHourlyFee { get; set; }
        public string otherHourlyFeeComments { get; set; }
        public Nullable<double> overtimeRate { get; set; }
        public decimal payRate { get; set; }
        public double recruitingManagerPercentGrossMargin { get; set; }
        public decimal referralFee { get; set; }
        public string referralFeeType { get; set; }
        public Nullable<double> reportedMargin { get; set; }
        public string reportTo { get; set; }
        public decimal salary { get; set; }
        public string salaryUnit { get; set; }
        public double salesManagerPercentGrossMargin { get; set; }
        public Nullable<int> statementClientContactID { get; set; }
        public string status { get; set; }
        public Nullable<double> taxRate { get; set; }
        public string taxState { get; set; }
        public string terminationReason { get; set; }
        public Nullable<int> workersCompRateID { get; set; }
        public Nullable<short> workWeekStart { get; set; }
        public Nullable<int> approvingClientContactID { get; set; }
        public Nullable<int> backupApprovingClientContactID { get; set; }
        public Nullable<int> vendorClientCorporationID { get; set; }
    }
}
