//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sendout
    {
        public int sendoutID { get; set; }
        public int candidateID { get; set; }
        public Nullable<int> clientContactID { get; set; }
        public Nullable<int> clientCorporationID { get; set; }
        public System.DateTime dateAdded { get; set; }
        public string email { get; set; }
        public short isRead { get; set; }
        public Nullable<int> jobOrderID { get; set; }
        public int userID { get; set; }
        public Nullable<int> userMessageID { get; set; }
    }
}
