//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialty
    {
        public int specialtyID { get; set; }
        public System.DateTime dateAdded { get; set; }
        public Nullable<short> enabled { get; set; }
        public string name { get; set; }
        public int parentCategoryID { get; set; }
        public int isDeleted { get; set; }
    }
}
