//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timecard
    {
        public int timecardID { get; set; }
        public string comments { get; set; }
        public System.DateTime dateAdded { get; set; }
        public System.DateTime dateBegin { get; set; }
        public System.DateTime dateEnd { get; set; }
        public Nullable<int> externalID { get; set; }
        public Nullable<int> invoiceID { get; set; }
        public int placementID { get; set; }
        public string status { get; set; }
        public Nullable<int> timecardBatchID { get; set; }
        public string type { get; set; }
    }
}
