//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimecardBatch
    {
        public int timecardBatchID { get; set; }
        public string batchName { get; set; }
        public System.DateTime dateAdded { get; set; }
        public short isDeleted { get; set; }
        public short isInvoiced { get; set; }
        public short isLocked { get; set; }
        public short isOpen { get; set; }
        public int ownerID { get; set; }
        public string status { get; set; }
    }
}
