//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimecardPayClass
    {
        public int payClassID { get; set; }
        public string billRateField { get; set; }
        public string classType { get; set; }
        public Nullable<double> clientMarkupFactor { get; set; }
        public string display { get; set; }
        public Nullable<short> enabled { get; set; }
        public Nullable<int> excludeFromInvoicing { get; set; }
        public Nullable<int> excludeFromPayrolling { get; set; }
        public Nullable<short> isRegularHoursClass { get; set; }
        public double markupFactor { get; set; }
        public string name { get; set; }
        public string payRateField { get; set; }
        public int privateLabelID { get; set; }
        public int sortOrder { get; set; }
    }
}
