//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataService314e
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimecardTime
    {
        public int timecardTimeID { get; set; }
        public Nullable<System.DateTime> breakEnd { get; set; }
        public Nullable<System.DateTime> breakStart { get; set; }
        public Nullable<double> clientBillRate { get; set; }
        public string comments { get; set; }
        public System.DateTime dateAdded { get; set; }
        public System.DateTime dateWorked { get; set; }
        public Nullable<int> fileExportID { get; set; }
        public double hours { get; set; }
        public Nullable<int> invoiceID { get; set; }
        public Nullable<int> invoiceItemID { get; set; }
        public Nullable<int> lastModifyingPersonID { get; set; }
        public Nullable<int> minutesBreak { get; set; }
        public int payClassID { get; set; }
        public Nullable<double> payRate { get; set; }
        public int placementID { get; set; }
        public string projectCode { get; set; }
        public string projectID { get; set; }
        public Nullable<int> timecardID { get; set; }
        public Nullable<System.DateTime> timeIn { get; set; }
        public Nullable<System.DateTime> timeOut { get; set; }
        public Nullable<double> workersCompensationRate { get; set; }
    }
}
